---
title: "08. Tree-Based Models"
author: "GS"
date: "23/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = F, warning = F, comment = "", fig.align = "center")
```

# An Introduction to Statistical Learning (2nd ed.)
### Labs

[An Introduction to Statistcial Learning](https://www.statlearning.com/)

[ISLR tidymodels Labs](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/linear-regression.html)

## Chapter 08
## Tree-based Models

```{r, packages}
library(tidymodels)
library(ISLR)
library(rpart.plot)
library(vip)

theme_set(theme_bw())
```

```{r, carseat dataset}
carseat <- tibble(Carseats)

glimpse(carseat)
knitr::kable(head(carseat))
```

```{r, splitting}
carseat <- carseat %>% 
  mutate(High = factor(if_else(Sales <=8, "No", "Yes"))) %>% 
  select(-Sales)

set.seed(2021)
car_split <- initial_split(carseat, prop = .75, strata = High)
car_train <- training(car_split)
car_test <- testing(car_split)
```

```{r, resamples}
car_folds <- vfold_cv(car_train, v = 10)
```


## Classification Tree

```{r, class tree model}
tree_clas_model <-
  decision_tree(cost_complexity = tune()) %>%
  set_engine('rpart') %>%
  set_mode('classification')

class_tree_wf <- 
  workflow() %>% 
  add_model(tree_clas_model) %>% 
  add_formula(High ~ .)

```

```{r, class tree fit, cache=TRUE}
param_grid <- grid_regular(cost_complexity(range = c(-3, -1)), levels = 10)

tree_class_tune <- 
  tune_grid(
    class_tree_wf,
    resamples = car_folds,
    grid = param_grid,
    metrics = metric_set(accuracy, roc_auc, mn_log_loss),
    control = control_grid(save_pred = T)
  )
```
```{r, class tree metrics}
autoplot(tree_class_tune)

tree_class_tune %>% collect_metrics()
tree_class_tune %>% collect_predictions()

tree_class_tune %>% show_best(metric = "accuracy")
best_class_tree <- tree_class_tune %>% select_best(metric = "accuracy")
```
```{r, class tree final wf}
class_tree_final_wf <-
  class_tree_wf %>% 
  finalize_workflow(best_class_tree)
```
```{r, class tree pred}
class_tree_fit <- 
  fit(class_tree_final_wf, car_train)

class_tree_pred <- augment(class_tree_fit, car_test)
class_tree_pred

class_tree_pred %>% conf_mat(truth = High, estimate = .pred_class)

class_tree_pred %>% accuracy(truth = High, estimate = .pred_class)
class_tree_pred %>% roc_auc(truth = High, estimate = .pred_No)

class_tree_pred %>% roc_curve(truth = High, estimate = .pred_No) %>% autoplot()

class_tree_fit %>% 
  extract_fit_engine() %>% 
  rpart.plot()
```



## Bagging and Random Forest

































[An Introduction to Statistcial Learning](https://www.statlearning.com/)

[ISLR tidymodels Labs](https://emilhvitfeldt.github.io/ISLR-tidymodels-labs/linear-regression.html)

-- END


```{r}
sessionInfo()
```

